{
  "comments": [
    {
      "key": {
        "uuid": "1fa4df85_0104a2c5",
        "filename": "lib/databases/mysql",
        "patchSetId": 1
      },
      "lineNbr": 132,
      "author": {
        "id": 4690
      },
      "writtenOn": "2020-03-12T22:00:23Z",
      "side": 1,
      "message": "If this works, add the bug link to this comment:\n\nhttps://bugs.launchpad.net/nova/+bug/1844929",
      "revId": "0b8b23d5a5e7b9a9aff3b1084eb9e70446321939",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}