{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "549b4470_914ec095",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 17685
      },
      "writtenOn": "2025-05-09T12:18:31Z",
      "side": 1,
      "message": "recheck - let\u0027s see if the errors were just some intermittent failures. two voting job failed:\n\ntempest-full-py3 - with 42 test case\ntempest-ipv6-only - with 1 test case:\n\nsetUpClass (tempest.api.compute.servers.test_create_server\nServersTestBootFromVolume)\nDetails: {\u0027code\u0027: 500, \u0027created\u0027: \u00272025-05-08T14:28:13Z\u0027, \u0027message\u0027: \u0027Exceeded maximum number of retries. Exhausted all hosts available for retrying build failures for instance e6c6ef41-5c40-445b-95c2-da6991608e85.\u0027}",
      "revId": "63b3be90f4f2415afe7df24a230b3373f717ef3e",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}