{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b584ce32_46299fc3",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 8556
      },
      "writtenOn": "2023-01-11T18:32:08Z",
      "side": 1,
      "message": "recheck ovn-nbctl: unix:/var/run/ovn/ovnnb_db.sock: database connection failure ",
      "revId": "69d71cfdf9c24d48fbea366714f4595cbd120723",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}