{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c7dadbf5_62e9f015",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5314
      },
      "writtenOn": "2022-04-20T16:22:31Z",
      "side": 1,
      "message": "LGTM.",
      "revId": "7f1025e932ac4529d2d604f71c6f6027feed8938",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "60ce5d32_56d73c29",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 17685
      },
      "writtenOn": "2022-04-21T08:03:25Z",
      "side": 1,
      "message": "recheck - timeout exception in test_snapshot_create_delete_with_volume_in_use\n\ntempest.lib.exceptions.TimeoutException: Request timed out\nDetails: (VolumesSnapshotTestJSON:test_snapshot_create_delete_with_volume_in_use) Failed to delete volume-snapshot 490abaee-958d-4dc1-96af-94945fcafe78 within the required time (196 s).",
      "revId": "7f1025e932ac4529d2d604f71c6f6027feed8938",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}