{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "99675c7a_a49eaded",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 13252
      },
      "writtenOn": "2022-02-02T14:21:55Z",
      "side": 1,
      "message": "recheck unrelated network error during log collection",
      "revId": "9c43f9fecc662444cc6b1083aa561fc00ffc8509",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "e6894348_3ca90f21",
        "filename": "tools/install_pip.sh",
        "patchSetId": 2
      },
      "lineNbr": 105,
      "author": {
        "id": 34451
      },
      "writtenOn": "2022-02-02T11:50:26Z",
      "side": 1,
      "message": "Low impact, It looks that python3_enabled function returns True in all stable version, but just to keep code consistency",
      "range": {
        "startLine": 105,
        "startChar": 26,
        "endLine": 105,
        "endChar": 36
      },
      "revId": "9c43f9fecc662444cc6b1083aa561fc00ffc8509",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}