{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "8249d5ed_c9ece887",
        "filename": "lib/nova",
        "patchSetId": 4
      },
      "lineNbr": 325,
      "author": {
        "id": 13252
      },
      "writtenOn": "2022-01-07T10:06:12Z",
      "side": 1,
      "message": "After looking a bit deeper, it seems that the kernel they use is too old (4.19.x), so this will hopefully get resolved by their next LTS release.",
      "revId": "ac958698d0e29cc0bc4bbad4476fc7bc01ed870d",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}