{
  "comments": [
    {
      "key": {
        "uuid": "3f79a3b5_ec947638",
        "filename": "stack.sh",
        "patchSetId": 1
      },
      "lineNbr": 1424,
      "author": {
        "id": 6873
      },
      "writtenOn": "2018-09-05T00:15:47Z",
      "side": 1,
      "message": "This seems to be hitting before we actually have compute nodes in the database, or the check isn\u0027t iterating the cells properly:\n\nhttp://logs.openstack.org/47/599847/1/check/tempest-full-py3/caf3557/controller/logs/devstacklog.txt.gz#_2018-09-04_22_05_45_875",
      "revId": "bde4024ba6f0d35837062614adbc085fa45a0fad",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3f79a3b5_acf99e80",
        "filename": "stack.sh",
        "patchSetId": 1
      },
      "lineNbr": 1424,
      "author": {
        "id": 6873
      },
      "writtenOn": "2018-09-05T00:26:37Z",
      "side": 1,
      "message": "Yeah the compute node on this same host was created before we run the check:\n\nhttp://logs.openstack.org/47/599847/1/check/tempest-full-py3/caf3557/controller/logs/screen-n-cpu.txt.gz#_Sep_04_22_05_02_228963\n\nby about 43 seconds, so the check isn\u0027t properly iterating cells or something...",
      "parentUuid": "3f79a3b5_ec947638",
      "revId": "bde4024ba6f0d35837062614adbc085fa45a0fad",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}